In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [3]:
world_df = pd.read_csv("world_data.csv")
world_df.head(20)

,country,year,iso_code,continent,status,population,hdi_rank_2021,hdi_2021,gdp,gdp_per_capita,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
0,Afghanistan,1900,AFG,Asia,developing,4832414.0,173,0.478,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,1901,AFG,Asia,developing,4879685.0,173,0.478,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,1902,AFG,Asia,developing,4935122.0,173,0.478,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,1903,AFG,Asia,developing,4998861.0,173,0.478,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,1904,AFG,Asia,developing,5063419.0,173,0.478,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Afghanistan,1905,AFG,Asia,developing,5128808.0,173,0.478,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Afghanistan,1906,AFG,Asia,developing,5195038.0,173,0.478,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Afghanistan,1907,AFG,Asia,developing,5262120.0,173,0.478,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Afghanistan,1908,AFG,Asia,developing,5330065.0,173,0.478,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Afghanistan,1909,AFG,Asia,developing,5467828.0,173,0.478,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Afghanistan,1910,AFG,Asia,developing,5681487.0,173,0.478,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Afghanistan,1911,AFG,Asia,developing,5977589.0,173,0.478,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Afghanistan,1912,AFG,Asia,developing,6363186.0,173,0.478,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Afghanistan,1913,AFG,Asia,developing,6845878.0,173,0.478,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Afghanistan,1914,AFG,Asia,developing,7365181.0,173,0.478,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Afghanistan,1915,AFG,Asia,developing,7923871.0,173,0.478,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Afghanistan,1916,AFG,Asia,developing,8524936.0,173,0.478,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Afghanistan,1917,AFG,Asia,developing,9171589.0,173,0.478,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Afghanistan,1918,AFG,Asia,developing,9875230.0,173,0.478,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Afghanistan,1919,AFG,Asia,developing,10338650.0,173,0.478,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
world_df.describe()

,year,population,hdi_rank_2021,hdi_2021,gdp,gdp_per_capita,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
count,13515.000000,1.351500e+04,13515.000000,13515.000000,1.000900e+04,10009.000000,500.000000,814.000000,838.000000,838.000000,...,4755.000000,4001.000000,1514.000000,3925.000000,4001.000000,6010.000000,6010.000000,4001.000000,4755.000000,4001.000000
mean,1970.527266,3.144088e+07,85.258454,0.743221,3.100552e+11,9875.860838,45.889302,1.286327,172.168959,17.502964,...,0.622449,0.131298,242.717921,1.226995,8.637403,52.811840,2.225099,182.987417,1.350967,0.476358
std,35.670914,1.102112e+08,53.687111,0.152110,1.117970e+12,12369.785557,293.914193,5.718617,281.927457,53.256099,...,2.065985,0.504596,6259.221920,11.070859,60.785173,223.668905,18.822214,661.732831,4.487012,1.712103
min,1900.000000,1.640900e+04,1.000000,0.385000,1.642060e+08,365.700000,-100.000000,-37.549000,0.000000,0.000000,...,0.000000,0.000000,-100.000000,-38.955000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1940.000000,2.663476e+06,37.000000,0.632000,1.425739e+10,2127.760000,-1.124250,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.274000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1979.000000,7.059804e+06,85.000000,0.758000,4.430539e+10,5516.550000,7.971500,0.000000,19.012500,1.726500,...,0.000000,0.000000,18.571500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2001.000000,2.070130e+07,128.000000,0.875000,1.840672e+11,12339.390000,27.562000,0.906750,264.369000,11.133500,...,0.048000,0.002000,50.000000,0.012000,0.203000,0.852750,0.010000,9.469000,0.160500,0.036000
max,2022.000000,1.425894e+09,184.000000,0.962000,1.815162e+13,166150.490000,5659.328000,60.875000,1747.467000,415.870000,...,25.735000,5.999000,242384.844000,490.329000,1715.493000,3219.852000,655.600000,7361.917000,56.840000,24.614000

In [6]:
def show_summary(df) :
    
    print(80 * "+")
    print(f"DIMENSIONS : ({df.shape[0]}, {df.shape[1]})")
    
    print(80 * "+")
    print("COULMNS: \n")
    print(df.columns.values)
    
    print(80 * "+")
    print("DATA INFO: \n")
    print(df.dtypes)
    
    print(80 * "+")
    print("MISSING VALUES: \n")
    print(df.isnull().sum())
    
    print(80 * "+")
    print("NUMBER OF UNIQUE VALUES: \n")
    print(df.nunique())

In [7]:
show_summary(world_df)

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
DIMENSIONS : (13515, 134)
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
COULMNS:

['country' 'year' 'iso_code' 'continent' 'status' 'population'
 'hdi_rank_2021' 'hdi_2021' 'gdp' 'gdp_per_capita'
 'biofuel_cons_change_pct' 'biofuel_cons_change_twh'
 'biofuel_cons_per_capita' 'biofuel_consumption' 'biofuel_elec_per_capita'
 'biofuel_electricity' 'biofuel_share_elec' 'biofuel_share_energy'
 'carbon_intensity_elec' 'coal_cons_change_pct' 'coal_cons_change_twh'
 'coal_cons_per_capita' 'coal_consumption' 'coal_elec_per_capita'
 'coal_electricity' 'coal_prod_change_pct' 'coal_prod_change_twh'
 'coal_prod_per_capita' 'coal_production' 'coal_share_elec'
 'coal_share_energy' 'electricity_demand' 'electricity_generation'
 'electricity_share_energy' 'energy_cons_change_pct'
 'energy_cons_change_twh' 'energy_per_capita' 'energy_per_gdp'
 'fossil_cons_change_pct' 'fossil_cons_change_twh'
 'fossil_elec_per_capita' 'fossil_electricity' 'fossil_energy_per_capita'
 'fossil_fuel_consumption' 'fossil_share_elec' 'fossil_share_energy'
 'gas_cons_change_pct' 'gas_cons_change_twh' 'gas_consumption'
 'gas_elec_per_capita' 'gas_electricity' 'gas_energy_per_capita'
 'gas_prod_change_pct' 'gas_prod_change_twh' 'gas_prod_per_capita'
 'gas_production' 'gas_share_elec' 'gas_share_energy'
 'greenhouse_gas_emissions' 'hydro_cons_change_pct'
 'hydro_cons_change_twh' 'hydro_consumption' 'hydro_elec_per_capita'
 'hydro_electricity' 'hydro_energy_per_capita' 'hydro_share_elec'
 'hydro_share_energy' 'low_carbon_cons_change_pct'
 'low_carbon_cons_change_twh' 'low_carbon_consumption'
 'low_carbon_elec_per_capita' 'low_carbon_electricity'
 'low_carbon_energy_per_capita' 'low_carbon_share_elec'
 'low_carbon_share_energy' 'net_elec_imports'
 'net_elec_imports_share_demand' 'nuclear_cons_change_pct'
 'nuclear_cons_change_twh' 'nuclear_consumption' 'nuclear_elec_per_capita'
 'nuclear_electricity' 'nuclear_energy_per_capita' 'nuclear_share_elec'
 'nuclear_share_energy' 'oil_cons_change_pct' 'oil_cons_change_twh'
 'oil_consumption' 'oil_elec_per_capita' 'oil_electricity'
 'oil_energy_per_capita' 'oil_prod_change_pct' 'oil_prod_change_twh'
 'oil_prod_per_capita' 'oil_production' 'oil_share_elec'
 'oil_share_energy' 'other_renewable_consumption'
 'other_renewable_electricity' 'other_renewable_exc_biofuel_electricity'
 'other_renewables_cons_change_pct' 'other_renewables_cons_change_twh'
 'other_renewables_elec_per_capita'
 'other_renewables_elec_per_capita_exc_biofuel'
 'other_renewables_energy_per_capita' 'other_renewables_share_elec'
 'other_renewables_share_elec_exc_biofuel' 'other_renewables_share_energy'
 'per_capita_electricity' 'primary_energy_consumption'
 'renewables_cons_change_pct' 'renewables_cons_change_twh'
 'renewables_consumption' 'renewables_elec_per_capita'
 'renewables_electricity' 'renewables_energy_per_capita'
 'renewables_share_elec' 'renewables_share_energy' 'solar_cons_change_pct'
 'solar_cons_change_twh' 'solar_consumption' 'solar_elec_per_capita'
 'solar_electricity' 'solar_energy_per_capita' 'solar_share_elec'
 'solar_share_energy' 'wind_cons_change_pct' 'wind_cons_change_twh'
 'wind_consumption' 'wind_elec_per_capita' 'wind_electricity'
 'wind_energy_per_capita' 'wind_share_elec' 'wind_share_energy']
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
DATA INFO:

country                    object
year                        int64
iso_code                   object
continent                  object
status                     object
                           ...
wind_elec_per_capita      float64
wind_electricity          float64
wind_energy_per_capita    float64
wind_share_elec           float64
wind_share_energy         float64
Length: 134, dtype: object
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
MISSING VALUES:

country                      0
year                         0
iso_code                     0
continent                    0
status                       0
                          ...
wind_elec_per_capita      7505
wind_electricity          7505
wind_energy_per_capita    9514
wind_share_elec           8760
wind_share_energy         9514
Length: 134, dtype: int64
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
NUMBER OF UNIQUE VALUES:

country                    165
year                       123
iso_code                   165
continent                    5
status                       2
                          ...
wind_elec_per_capita      1667
wind_electricity           659
wind_energy_per_capita    1529
wind_share_elec           1203
wind_share_energy          822
Length: 134, dtype: int64

Subset world_df into diferrent dataframe based on energy source

In [12]:
# function to subset based on the energy source
def subset_energy_source(df: pd.DataFrame, source :str) -> pd.DataFrame:
    
    source_col = df.filter(like=source).columns
    new_df = df[['country', 'year', 'iso_code', 'continent', 'status', 'population', 'hdi_rank_2021', 'hdi_2021', 'gdp', 'gdp_per_capita'] + list(source_col)]
    
    return new_df

In [16]:
coal_df = subset_energy_source(world_df, "coal")
biofuel_df = subset_energy_source(world_df, "biofuel")
gas_df = subset_energy_source(world_df, "gas")
hydro_df = subset_energy_source(world_df, "hydro")
low_carbon_df = subset_energy_source(world_df,  "low_carbon")
nuclear_df = subset_energy_source(world_df, "nuclear")
oil_df = subset_energy_source(world_df, "nuclear")
solar_df = subset_energy_source(world_df, "solar")
wind_df = subset_energy_source(world_df, "wind")

In [17]:
coal_df.describe()

,year,population,hdi_rank_2021,hdi_2021,gdp,gdp_per_capita,coal_cons_change_pct,coal_cons_change_twh,coal_cons_per_capita,coal_consumption,coal_elec_per_capita,coal_electricity,coal_prod_change_pct,coal_prod_change_twh,coal_prod_per_capita,coal_production,coal_share_elec,coal_share_energy
count,13515.000000,1.351500e+04,13515.000000,13515.000000,1.000900e+04,10009.000000,3683.000000,3949.000000,4025.000000,4025.000000,4340.000000,4340.000000,5868.000000,10469.000000,10634.000000,10634.000000,4339.000000,4025.000000
mean,1970.527266,3.144088e+07,85.258454,0.743221,3.100552e+11,9875.860838,32.478422,6.861445,5888.200830,375.737962,710.691970,56.336994,27.267301,3.490437,3273.281914,196.734620,15.699632,17.558358
std,35.670914,1.102112e+08,53.687111,0.152110,1.117970e+12,12369.785557,954.746377,91.162682,9055.334784,1623.233243,1358.750282,301.357142,799.902036,75.890382,9721.041636,1047.374753,24.721545,20.136070
min,1900.000000,1.640900e+04,1.000000,0.385000,1.642060e+08,365.700000,-100.000000,-750.678000,0.000000,0.000000,0.000000,0.000000,-100.000000,-1602.727000,0.000000,0.000000,0.000000,0.000000
25%,1940.000000,2.663476e+06,37.000000,0.632000,1.425739e+10,2127.760000,-5.997500,-1.137000,237.197000,4.248000,0.000000,0.000000,-5.799750,0.000000,0.000000,0.000000,0.000000,2.075000
50%,1979.000000,7.059804e+06,85.000000,0.758000,4.430539e+10,5516.550000,0.872000,0.006000,2369.002000,32.584000,0.000000,0.000000,1.882500,0.000000,21.777500,0.252000,0.000000,9.922000
75%,2001.000000,2.070130e+07,128.000000,0.875000,1.840672e+11,12339.390000,8.364000,3.315000,8119.868000,149.632000,810.172500,14.309250,10.593750,0.195000,1410.265750,20.230500,25.403500,25.803000
max,2022.000000,1.425894e+09,184.000000,0.962000,1.815162e+13,166150.490000,55400.000000,2249.825000,96169.938000,23936.059000,9103.898000,5339.140000,44965.750000,2167.818000,151662.281000,23651.393000,100.000000,89.139000